### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by mzoller** [snellen/o-events.net#4]
Features that could be added, but are not vital for the project:
- "Forgot password" function. Sends an e-mail with a link that will allow the user to reset the password.
- Nice country selector with flags.
- Tooltips that provide help for specific form fields. The fields should have a "(?)" button next to them, which has to be clicked to view the tooltip.
- A help, maybe as a Wiki (so we don't have to write it all ourselves). The help should support i18n, so MediaWiki is probably a bad choice.
- Login using the SOLV number for Swiss competitors.
- An event setting to define which timestamp is relevant for the registration deadline: The time of registration or the time of payment. This is especially important in events with multiple deadlines. Both cases occur: In events without e-payment, only the registration time is available, whereas in large events like Swiss O Week, the time of payment is relevant for the start fee amount.
- Age limits for categories are currently defined by year only. The organizer should have the option to define them by exact date (as a per-event setting), and the user should see how the limits are defined. Also, the year of birth should be mandatory if age limits are used, and the entire date of birth should be mandatory if the limits are date-dependent.
- Ideally there would be a way for the user to define their own validations for the custom fields. As an example, the data structure does not support school grade, so the grade (Klasse) has to be stored in num1...num3. However, it should be possible to validate that only students in certain grades may compete in a category. This is not feasible without some kind of scripting language, though...

**Comment by snellen** [comment]
Set correct exchange rate when creating a bill.
