### ISSUE TITLE
Data model issue!!

### ISSUE THREAD

**Issue by mzoller** [snellen/o-events.net#7]
There is a problem with the current definition of CompetitionGroups.
- The competition groups are groups of competitions that have the same categories, start fees, and team pool.
- Registrations are still per competition, i.e. teams can choose in which competition they want to participate.
- The problem is that in some events, the start fees are different in each competition, but the teams should be the same. This is currently not possible.
- **Example:** An event has three competitions with separate start fee definitions. The competitions must therefore be in three separate competition groups. However all three competitions are for single competitors, so it does not make sense to keep separate competitor databases. With the current DB structure, users would have to enter their data three times, rather than entering it once and selecting the competitions they want to participate in.
- **Solution:** There are several solutions I can think of.
  1. Go back to a former definition of competition groups: All competitions in a group have the same categories and the same start fees, but teams are defined on event level. The drawback here is that the categories have to be copied if two competitions have the same categories, but not the same start fees (which is a quite common case). And of course it is no longer possible to combine team competitions with individual competitions in one event.
  2. Introduce a flag in competition groups that allows for individual start fees in each competition. The categories and teams would still be shared between all competitions in a group. This also has a drawback: The user may have to enter the same start fees several times, e.g. if only one of seven competitions in a group has special start fees. Furthermore, the StartFees table would have to reference either a CompetitionGroup or a Competition, depending on the flag.
  3. Divide the CompetitionGroup entity in two: Create a TeamPool entity which is linked to teams and categories, and let it have several CompetitionGroups which are linked to StartFees. I think this is the only clean solution to the problem, even though it complicates the data model.

**Comment by snellen** [comment]
resolved with approach number 3 -> closed
